### ISSUE TITLE
Running webdiff on a server / generating diffs

### ISSUE THREAD

**Issue by michalskop** [danvk/webdiff#123]
I wonder if it is possible to run webdiff on a webserver so it is accessible publicly? E.g., to be able to show differences between versions of a text in my git project.

I also tried to save the locally produced webpage ( Save `Complete webpage` after running `git webdiff <left> <right> text.txt`), but it is not shown on a (different) webserver anyway (it's shown for a second or less and than it disappears).

**Comment by daytonb** [comment]
I'm not sure I completely understand. You can create/edit a config file for webdiff that will serve its diff on your computer's hostname so other who can resolve your hostname can access the diff in a browser. If the machine is on a public internet then anyone could browse to your hostname and specified port.

If you want it to be something where people on the public internet to initiate the webdiff rather than you initiating it, I don't know how to do that. It feels possible, but I haven't really done any web development myself yet.

**Comment by berrabe** [comment]
I just found a way to make webdiff publicly accessible on a server without random port

<p align="center">
  <img src="https://user-images.githubusercontent.com/34432326/116965489-26df1680-acd8-11eb-935e-481c66187b6e.png">
</p>

with just 3 easy steps:
1 - make config dir and several files ( dotfiles ), mine is in `$HOME/.config/webdiff`
2 - copy the configs directive as shown in the picture ( `git-webdiff.sh` and `webdiff.sh` is the same file except on `which` command ... `git-websiff.sh` use `$(which git-webdiff) $*` )
3 - make alias for webdiff and git-webdiff
